contacts_list:
    path:       /admin/questions/{iPage}
    controller: App\Controller\AdminController::questions
    defaults:
        iPage: 1
    requirements:
        iPage: \d+
        
treat_question:
    path:       /admin/treat_question
    controller: App\Controller\AdminController::treatQuestion

contact:
    path:       /contact
    controller: App\Controller\ContactController::getContactForm

login:
    path:       /login
    controller: App\Controller\SecurityController::login

logout:
    path:       /logout
